### ISSUE TITLE
Error Finding AWS Credentials

### ISSUE THREAD

**Issue by dtothefp** [DataDog/datadog-lambda-js#104]
## Expected Behavior
Wrap the handler with `{ datadog }` function and see logs when supplying forwarder ARN from 

## Actual Behavior
Used the example

```js
const messageToObject = (stringMessage) => {
  const { message, status, ...metadata } = JSON.parse(stringMessage); // eslint-disable-line @typescript-eslint/no-unused-vars

  return [metadata, message];
};

const wrapper = (handler) => {
  const logger = pino();

  return datadog(handler, {
    logger: {
      debug: (message) => logger.debug(...messageToObject(message)),
      error: (message) => logger.error(...messageToObject(message)),
    },
  });
};

exports.handler = wrapper(handler);
```

I'm also using Pino to log messages to STDOUT within the handler, not sure if that's the issue?

## Steps to Reproduce the Problem

  1. This was working previously and stopped. I'm not sure if something changed in our config but help debugging would be useful.

## Specifications

  - Datadog Lambda Layer version: ?
  - Node version: 12.x
  
## Stacktrace
  
  ```
{"error.msg":"ENOENT: no such file or directory, open '/home/sbx_user1051/.aws/credentials'","error.type":"Error","error.stack":"Error: ENOENT: no such file or directory, open '/home/sbx_user1051/.aws/credentials'\n    at Object.openSync (fs.js:462:3)\n    at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:93:53\n    at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:45:56\n    at Scope._activate (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/scope/async_hooks.js:53:14)\n    at Scope.activate (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:12:19)\n    at DatadogTracer.trace (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:45:35)\n    at Object.openSync (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:93:23)\n    at Object.readFileSync (fs.js:364:35)\n    at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:93:53\n    at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:45:56","_dd.origin":"lambda","service":"discovery-optimizely-fullstack-ab-test-prod-datafile-webhook","component":"fs","span.kind":"internal","file.path":"/var/task/node_modules/aws-xray-sdk-core/lib/middleware/sampling/local_reservoir.js","file.flag":"r"},"metrics":{"_sample_rate":1,"_sampling_priority_v1":1},"start":1601447535843548400,"duration":448730,"service":"discovery-optimizely-fullstack-ab-test-prod-datafile-webhook-fs"},{"trace_id":"2404f81bae32c2eb","span_id":"0d2b6d4b62711afa","parent_id":"2c970dd2db1d990a","name":"fs.operation","resource":"openSync","error":0,"meta":{"error.msg":"ENOENT: no such file or directory, open '/home/sbx_user1051/.aws/config'","error.type":"Error","error.stack":"Error: ENOENT: no such file or directory, open '/home/sbx_user1051/.aws/config'\n    at Object.openSync (fs.js:462:3)\n    at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:93:53\n    at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:45:56\n    at Scope._activate (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/scope/async_hooks.js:53:14)\n    at Scope.activate (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:12:19)\n    at DatadogTracer.trace (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:45:35)\n    at Object.openSync (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:93:23)\n    at Object.readFileSync (fs.js:364:35)\n    at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:93:53\n    at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:45:56","_dd.origin":"lambda","service":"discovery-optimizely-fullstack-ab-test-prod-datafile-webhook","component":"fs","span.kind":"internal","file.path":"/var/task/node_modules/aws-xray-sdk-core/lib/middleware/sampling/local_reservoir.js","file.flag":"r"},"metrics":{"_sample_rate":1,"_sampling_priority_v1":1},"start":1601447535849416700,"duration":176270,"service":"discovery-optimizely-fullstack-ab-test-prod-datafile-webhook-fs"},{"trace_id":"2404f81bae32c2eb","span_id":"2c970dd2db1d990a","parent_id":"5e5ecd342765cae7","name":"fs.operation","resource":"readFileSync","error":0,"meta":{"error.msg":"ENOENT: no such file or directory, open '/home/sbx_user1051/.aws/config'","error.type":"Error","error.stack":"Error: ENOENT: no such file or directory, open '/home/sbx_user1051/.aws/config'\n    at Object.openSync (fs.js:462:3)\n    at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:93:53\n    at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:45:56\n    at Scope._activate (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/scope/async_hooks.js:53:14)\n    at Scope.activate (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:12:19)\n    at DatadogTracer.trace (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:45:35)\n    at Object.openSync (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:93:23)\n    at Object.readFileSync (fs.js:364:35)\n    at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:93:53\n    at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:45:56","_dd.origin":"lambda","service":"discovery-optimizely-fullstack-ab-test-prod-datafile-webhook","component":"fs","span.kind":"internal","file.path":"/var/task/node_modules/aws-xray-sdk-core/lib/middleware/sampling/local_reservoir.js","file.flag":"r"}
  ```

**Comment by tianchu** [comment]
@dtothefp So sorry for the super late reply, and we are definitely improving our internal process of tracking github issues!

Do you still experience this issue? Otherwise, I would close it in a few days, since there hasn't been similar reports from other users.

**Comment by tianchu** [comment]
Closing for now, since no similar report of the same issue. Feel free to reopen or follow up for a deeper investigation by joining our [Slack community](https://github.com/DataDog/datadog-lambda-js#community).
