### ISSUE TITLE
Datadog layer arn:aws:lambda:<AWS_REGION>:464622532012:layer:Datadog-Node16-x:84 is broken

### ISSUE THREAD

**Issue by j2fong** [DataDog/datadog-lambda-js#310]
## Expected Behavior
No datadog error in lambda runtime

## Actual Behavior
lambda crashes with exception from datadog in datadog-lambda-js/runtime/user-function.js:16:65

## Steps to Reproduce the Problem

  1. Install according to https://docs.datadoghq.com/serverless/installation/nodejs/?tab=serverlessframework
  2. serverless deploy lambda to AWS
  3. run lambda

## Specifications

  - Datadog Lambda Layer version:  arn:aws:lambda:<AWS_REGION>:464622532012:layer:Datadog-Node16-x:84
  - Node version: 16.15.1

## Stacktrace

  ```
{"timestamp":1665532393275,"message":"2022-10-11T23:53:13.275Z\tundefined\tERROR\tUncaught Exception \t{\"errorType\":\"Runtime.ImportModuleError\",\"errorMessage\":\"Error: Cannot find module 'hot-shots'\
Require stack:\
- /var/task/node_modules/datadog-lambda-js/dist/metrics/listener.js\
- /var/task/node_modules/datadog-lambda-js/dist/metrics/index.js\
- /var/task/node_modules/datadog-lambda-js/dist/index.js\
- /var/task/libs/logger.js\
- /var/task/connectors/weather.js\
- /opt/nodejs/node_modules/datadog-lambda-js/runtime/user-function.js\
- /opt/nodejs/node_modules/datadog-lambda-js/runtime/index.js\",\"stack\":[\"Runtime.ImportModuleError: Error: Cannot find module 'hot-shots'\",\"Require stack:\",\"- /var/task/node_modules/datadog-lambda-js/dist/metrics/listener.js\",\"- /var/task/node_modules/datadog-lambda-js/dist/metrics/index.js\",\"- /var/task/node_modules/datadog-lambda-js/dist/index.js\",\"- /var/task/libs/logger.js\",\"- /var/task/connectors/weather.js\",\"- /opt/nodejs/node_modules/datadog-lambda-js/runtime/user-function.js\",\"- /opt/nodejs/node_modules/datadog-lambda-js/runtime/index.js\",\"    at ImportModuleError.ExtendedError [as constructor] (/opt/nodejs/node_modules/datadog-lambda-js/runtime/errors.js:113:28)\",\"    at new ImportModuleError (/opt/nodejs/node_modules/datadog-lambda-js/runtime/errors.js:123:42)\",\"    at /opt/nodejs/node_modules/datadog-lambda-js/runtime/user-function.js:273:31\",\"    at step (/opt/nodejs/node_modules/datadog-lambda-js/runtime/user-function.js:43:23)\",\"    at Object.throw (/opt/nodejs/node_modules/datadog-lambda-js/runtime/user-function.js:24:53)\",\"    at rejected (/opt/nodejs/node_modules/datadog-lambda-js/runtime/user-function.js:16:65)\"]}","requestID":"undefined","logStream":"2022/10/11/[$LATEST]dff7ce6763dd4a4aa1b4a54dbf7c93f2","logGroup":"/aws/lambda/myLambda"}
  ```

**Comment by j2fong** [comment]
User error, it was using the wrong package in the current layer
