### ISSUE TITLE
Getting 413 from Datadog when sending metrics

### ISSUE THREAD

**Issue by aaleksandrov** [DataDog/datadog-lambda-js#491]
## Expected Behavior
We send metrics from lambda to Datadog using `sendDistributionMetricWithDate` (it could be 10k metrics within one invocation). We expect to see metrics on Datadog 

## Actual Behavior
We receive 413
message | datadog:failed attempt to send metrics to Datadog. HTTP error code: 413

I see [a similar issue](https://github.com/DataDog/datadogpy/issues/465) was raised for the python library and it was fixed by implementing compression. is it possible to do the same?

## Steps to Reproduce the Problem

Send too many metrics

## Specifications

  - We are not using layer, we use this library directly, version 7.104.0
  - Node version: latest node20 supported by lambda

## Stacktrace

  ```
......:/aws/lambda/anomaly-detection-prod
2024/02/27/[$LATEST]3bcabca478e6484eba931ad8693a0dfb
2024-02-27T14:13:49.022Z	5bfee822-85f3-4b9c-a480-ca79831b8afe	ERROR	[dd.trace_id=763581508228917774 dd.span_id=4987919669838945685] {"status":"error","message":"Failed to send metrics to Datadog","name":"Error","stack":"Error: Failed to send metrics to Datadog\n    at Processor.<anonymous> (/var/task/node_modules/datadog-lambda-js/src/metrics/processor.ts:96:13)\n    at step (/var/task/node_modules/datadog-lambda-js/dist/metrics/processor.js:33:23)\n    at Object.throw (/var/task/node_modules/datadog-lambda-js/dist/metrics/processor.js:14:53)\n    at rejected (/var/task/node_modules/datadog-lambda-js/dist/metrics/processor.js:6:65)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}
.js:6:65)    at processTicksAndRejections (node:internal/process/task_queues:95:5)
error

  ```

**Comment by astuyve** [comment]
Hey @aaleksandrov, thanks for this note. We can definitely enable compression, metrics should compress well.

For anyone who may find this ticket and want to work on it, I believe we'd simply need to gzip the payload and set the `Content-Encoding: deflate` header, as per [this pr](https://github.com/DataDog/datadogpy/pull/466/files#diff-7638d40c850efd8f3ade8a161de03108a3f15de4de8c1c9751050eb086003d7aR143-R145).

Thanks!

**Comment by aaleksandrov** [comment]
@astuyve Could you check the related PR please?  https://github.com/DataDog/datadog-lambda-js/pull/492

**Comment by astuyve** [comment]
This is out in [v8.107.0](https://github.com/DataDog/datadog-lambda-js/releases/tag/v8.107.0).

Thanks again for the contribution!
