### ISSUE TITLE
Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by AlanAlvarez5** [DataDog/datadog-lambda-js#572]
## Expected Behavior
Normal flow, performing traces and regular behavior.

## Actual Behavior
Throws error, before running lambda code. "Class extends value undefined is not a constructor or null"

## Steps to Reproduce the Problem

  1. Use a serverless template with datadog-plugin
  2. Make a process with typeORM to perform CRUD operations at any database

## Specifications

  - Serverless Framework version: 3
  - Datadog Serverless Plugin version: latest
  - Lambda function runtime (Python 3.7, Node 10, etc.):  Node 20.x
  
## Stacktrace
  
  ```
  {
    "errorType": "TypeError",
    "errorMessage": "Class extends value undefined is not a constructor or null",
    "stack": [
        "TypeError: Class extends value undefined is not a constructor or null",
        "    at Object.<anonymous> (/opt/nodejs/node_modules/path-scurry/dist/commonjs/index.js:124:40)",
        "    at Module._compile (node:internal/modules/cjs/loader:1358:14)",
        "    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)",
        "    at Module.load (node:internal/modules/cjs/loader:1208:32)",
        "    at Module._load (node:internal/modules/cjs/loader:1024:12)",
        "    at Module.require (node:internal/modules/cjs/loader:1233:19)",
        "    at Hook.Module.require (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/ritm.js:97:33)",
        "    at require (node:internal/modules/helpers:179:18)",
        "    at Object.<anonymous> (/opt/nodejs/node_modules/glob/dist/commonjs/glob.js:6:23)",
        "    at Module._compile (node:internal/modules/cjs/loader:1358:14)"
    ]
}
  ```

**Comment by purple4reina** [comment]
Hey @AlanAlvarez5, 

I have an update for you. I spoke with the team and we think this issue might be caused by [dependency collisions](https://aaronstuyvenberg.com/posts/why-you-should-not-use-lambda-layers#dependency-collisions) when using lambda layers.

I assume the collision is happening with `lru-cache`, so let's look at it more closely. `dd-trace` requires `lru-cache` version `^7.14.0` whereas `typeorm` requires `glob` which requires `path-scurry` which requires `lru-cache` version `^10.2.0`.

I assume you are uploading the dependencies by including the `node_modules` in your lambda package zip. When aws installs this code in the lambda container, it does so at `/var/task`, meaning you'll find `lru-cache` version `^10.2.0` at `/var/task/node_modules/lru_cache`. Next comes the lambda layers, which includes the datadog layer and dependencies. These get installed at `/opt`, meaning you'll find `lru-cache` version `^7.14.0` at `/opt/node_modules/lru_cache`. 

Finally it is time to execute your function. When resolving dependencies, the runtime looks in `/var/task` first and if not found there will go search in `/opt` next. Since `dd-trace` works by hooking into the import system, the second you import anything, `dd-trace` is called which needs `lru-cache`. But instead of finding version `^7.14.0` in `/opt`, version `^10.2.0` is instead found first at `/var/task` and therefore used. This leads to the error you are getting.

I suspect the reason why downgrading `typeorm` fixes things is because version `0.3.17` requires a lower version of `lru-cache` than `0.3.20` does and `dd-trace` works fine with this lower version.

So what do you do about this? Stop using the Datadog lambda layer and instead install the Datadog dependencies yourself alongside all your other dependencies. To do so, you will instruct the Datadog plugin not to install the layer by including this in your `serverless.yml` file:

```yml
custom:
  datadog:
    addLayers: false
```

Then, include `datadog-lambda-js` in your `package.json` file as a dependency and redeploy.

Let me know how this works out.

**Comment by astuyve** [comment]
Closing as we've had no response and believe we've identified the issue

**Comment by atjchen** [comment]
Hello, on my project, I have exactly the same issue with a Datadog layer and a TypeORM layer. If I understand correctly, you don't have any other solution to suggest apart from removing Datadog layer (or the TypeORM one)?

**Comment by purple4reina** [comment]
@atjchen as stated before, in order to avoid the dependency collision, you'll want to stop using the Datadog lambda layer and instead install the Datadog dependencies yourself alongside all your other dependencies. To do so, you will instruct the Datadog plugin not to install the layer by including this in your serverless.yml file:

```yaml
custom:
  datadog:
    addLayers: false
```

Then, include `datadog-lambda-js` in your package.json file as a dependency and redeploy.
